modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="phantom_jammer"
version="0.0.1.0"
displayName="Phantom Jammer"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="300f20t, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.phantom_jammer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration